FROM node:12

WORKDIR /app

COPY package*.json /app/
RUN npm install

COPY . /app/

CMD [ "node", "main.js" ]

EXPOSE 8082

COPY ./ports.conf /etc/apache2/ports.conf
COPY ./apache.conf /etc/apache2/sites-enabled/000-default.conf